version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: inventory_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
      POSTGRES_DB: inventory_db
    volumes:
      - inventory_data:/var/lib/postgresql/data

volumes:
  inventory_data: {}
